title: Isaac Hernandez # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ACERCA DE MI 👨‍💻
  Hola, soy Isacc Danger Hernández, un apasionado desarrollador y ServerAdmin. 
  Mi enfoque principal está en ser un todo terreno, y tengo un sólido conocimiento Python. 
  Me encanta utilizar esta tecnología para crear soluciones eficientes y escalables. 
  Además, actualmente estoy dedicando tiempo y esfuerzo en aprender FastApi, un popular framework de python 
  para el desarrollo web. Estoy emocionado por ampliar mis habilidades y aprovechar al máximo las 
  capacidades de Python en mis proyectos. Soy un apasionado de la programación y siempre estoy 
  buscando nuevas formas de mejorar y expandir mis conocimientos. Estoy listo para enfrentar 
  desafíos y colaborar en equipos de desarrollo para crear aplicaciones innovadoras.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  [Mi CV](http://example.com/)
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
